apiVersion: v1
kind: Service
metadata:
  name: admin-server
  labels:
    app: admin-server
spec:
  selector:
    app: admin-server
  ports:
    - port: 9090
      targetPort: 9090
      name: http
  type: ClusterIP
